services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data/db

volumes:
  mongo: null